services:
  recipient-service:
    image: recipient-service
    container_name: recipient-service
    build:
      context: .
      dockerfile: recipient-service/Dockerfile
    ports:
      - 8080:8080
    depends_on:
      recipient-service-postgres:
        condition: service_started
  recipient-service-postgres:
    image: postgres:latest
    container_name: recipient-service-postgres
    restart: always
    ports:
      - 5432:5432
    volumes:
      - /Users/merlin/Volumes/docker/postgres:/var/lib/postgresql/recipient-service-postgres/data
    environment:
      - POSTGRES_PASSWORD=postgres